{% set version = "0.1.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-transformr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/transformr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/transformr/transformr_{{ version }}.tar.gz
  sha256: bcbbaa30140d5f75306b800521d597391a8fe5b764a4f33416e9ee77794abe88

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp >=0.12.15             # [build_platform != target_platform]
    - r-lpsolve                    # [build_platform != target_platform]
    - r-rlang                      # [build_platform != target_platform]
    - r-sf                         # [build_platform != target_platform]
    - r-tweenr                     # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=0.12.15
    - r-lpsolve
    - r-rlang
    - r-sf
    - r-tweenr
  run:
    - r-base
    - r-rcpp >=0.12.15
    - r-lpsolve
    - r-rlang
    - r-sf
    - r-tweenr

test:
  commands:
    - $R -e "library('transformr')"           # [not win]
    - "\"%R%\" -e \"library('transformr')\""  # [win]

about:
  home: https://github.com/thomasp85/transformr
  license: MIT
  summary: In order to smoothly animate the transformation of polygons and paths, many aspects needs to be taken into account, such as differing number of control points, changing center of rotation, etc. The 'transformr' package provides an extensive framework for manipulating the shapes of polygons and paths and can be
    seen as the spatial brother to the 'tweenr' package.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: transformr
# Type: Package
# Title: Polygon and Path Transformations
# Version: 0.1.3
# Authors@R: person(given = "Thomas Lin", family = "Pedersen", role = c("cre", "aut"), email = "thomasp85@gmail.com", comment = c(ORCID = "0000-0002-5147-4711"))
# Maintainer: Thomas Lin Pedersen <thomasp85@gmail.com>
# Description: In order to smoothly animate the transformation of polygons and paths, many aspects needs to be taken into account, such as differing number of control points, changing center of rotation, etc. The 'transformr' package provides an extensive framework for manipulating the shapes of polygons and paths and can be seen as the spatial brother to the 'tweenr' package.
# License: MIT + file LICENSE
# Encoding: UTF-8
# SystemRequirements: C++11
# LazyData: true
# Imports: Rcpp (>= 0.12.15), tweenr, rlang, sf, lpSolve
# Suggests: magrittr
# LinkingTo: Rcpp
# RoxygenNote: 7.1.0.9000
# URL: https://github.com/thomasp85/transformr
# BugReports: https://github.com/thomasp85/transformr/issues
# NeedsCompilation: yes
# Packaged: 2020-07-05 18:02:59 UTC; thomas
# Author: Thomas Lin Pedersen [cre, aut] (<https://orcid.org/0000-0002-5147-4711>)
# Repository: CRAN
# Date/Publication: 2020-07-05 18:20:03 UTC
